### ISSUE TITLE
Make new database table for "species"

### ISSUE THREAD

**Issue by sopanhavuth-aka-sam** [sopanhavuth-aka-sam/ATDDproject#6]
create new table for information below:
(and yes, #3 and #5 is the same species. This is how it is set up by SharkLab)
1. White Shark (Carcharodon carcharias)
2. California Sheephead (Semicossyphus pulcher)
3. White Croaker (Genyonemus lineatus)
4. Green Sea Turtle (Chelonia mydas)
5. White Croaker (Genyonemus lineatus)
6. California Halibut (Paralichthys californicus) 
7. Cowcod (Sebastes levis)
8. Bocaccio (Sebastes paucispinus)
9. Shovelnose Guitarfish (Rhinobatos productus) 
10. California Bat Ray (Myliobatis californica)
11. Barred Sand Bass (Paralarax nubilifer)

**Comment by mhopps108** [comment]
created species.csv and loaded into species table in group DB
